#!/bin/bash
#PBS -P xv83
#PBS -q normal
#PBS -l walltime=20:00:00
#PBS -l mem=50GB
#PBS -l storage=gdata/xv83+gdata/rt52
#PBS -l wd

# Example: qsub preprocess_era5_nci.job

__conda_setup="$('/g/data/xv83/dbi599/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/g/data/xv83/dbi599/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/g/data/xv83/dbi599/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/g/data/xv83/dbi599/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup

conda activate unseen

python preprocess_era5_nci.py msl single-levels 12 /g/data/xv83/dbi599/msl_era5_oper_sfc_12UTC_19400101-20251130.nc




